Does not allow __read_write in SYCL mode
For now there is a conflict with an argument named "__read_write":
In file included from /usr/include/stdio.h:74:
/usr/include/libio.h:376:67: error: access qualifier can only be used for pipe
      and image type
extern void _IO_cookie_init (struct _IO_cookie_file *__cfile, int __read_write,